/**
 * @eloquentjs/codegen — OpenAPI 3.0 Template
 *
 * Generates an OpenAPI 3.0 spec object from ModelSchemas.
 * CLI: eloquent generate:openapi
 */

/**
 * Generate OpenAPI 3.0 spec for one or more models.
 * Reflects the routes generated by @eloquentjs/api.
 * @param {ModelSchema[]} schemas
 * @param {object} opts
 * @returns {object} — OpenAPI 3.0 spec object (JSON-serializable)
 */
export function generateOpenApiSpec(schemas, opts = {}) {
  const {
    title       = 'EloquentJS API',
    version     = '1.0.0',
    description = 'Auto-generated from EloquentJS models',
    servers     = [{ url: 'http://localhost:3000/api', description: 'Development' }],
    prefix      = '/api',
    security    = null,    // e.g. [{ bearerAuth: [] }]
    header      = true,
  } = opts

  const spec = {
    openapi: '3.0.3',
    info: { title, version, description },
    servers,
    tags: [],
    paths: {},
    components: {
      schemas: {},
      securitySchemes: security ? {
        bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
      } : undefined,
    },
  }

  if (security) spec.security = security

  for (const schema of schemas) {
    const { name, fields, softDeletes } = schema
    const singular = lcFirst(name)
    const plural   = toKebab(name) + 's'
    const basePath = `${prefix}/${plural}`

    spec.tags.push({ name, description: `${name} resource endpoints` })

    // ── Component schemas ─────────────────────────────────────────────────
    const visibleFields = fields.filter(f => !f.hidden)

    // Full response schema
    spec.components.schemas[name] = {
      type: 'object',
      properties: Object.fromEntries(
        visibleFields.map(f => [
          f.name,
          { ...f.openApiType, ...(f.nullable ? {} : {}) },
        ])
      ),
    }

    // Create input schema
    const createFields = fields.filter(f => !f.isPk && !f.isTimestamp && !f.isSoftDelete && !f.hidden)
    spec.components.schemas[`Create${name}Input`] = {
      type: 'object',
      properties: Object.fromEntries(createFields.map(f => [f.name, f.openApiType])),
    }

    // Update input schema (all optional)
    spec.components.schemas[`Update${name}Input`] = {
      type: 'object',
      properties: Object.fromEntries(createFields.map(f => [f.name, f.openApiType])),
    }

    // Paginated response
    spec.components.schemas[`${name}Page`] = {
      type: 'object',
      properties: {
        data: { type: 'array', items: { '$ref': `#/components/schemas/${name}` } },
        meta: { '$ref': '#/components/schemas/PaginationMeta' },
      },
    }

    // ── Paths ─────────────────────────────────────────────────────────────
    const securityDef = security ? { security } : {}
    const tag = [name]

    // GET /resources (index)
    // POST /resources (store)
    spec.paths[basePath] = {
      get: {
        tags: tag, summary: `List ${name} records`, operationId: `list${name}`,
        ...securityDef,
        parameters: [
          { name: 'page',     in: 'query', schema: { type: 'integer', default: 1 } },
          { name: 'per_page', in: 'query', schema: { type: 'integer', default: 15 } },
          { name: 'search',   in: 'query', schema: { type: 'string' } },
          { name: 'sort',     in: 'query', schema: { type: 'string' }, description: 'Field to sort by. Prefix with - for descending.' },
          { name: 'with',     in: 'query', schema: { type: 'string' }, description: 'Comma-separated relations to eager load.' },
        ],
        responses: {
          200: {
            description: `Paginated list of ${name} records`,
            content: { 'application/json': { schema: { '$ref': `#/components/schemas/${name}Page` } } },
          },
        },
      },
      post: {
        tags: tag, summary: `Create a ${name}`, operationId: `create${name}`,
        ...securityDef,
        requestBody: {
          required: true,
          content: { 'application/json': { schema: { '$ref': `#/components/schemas/Create${name}Input` } } },
        },
        responses: {
          201: {
            description: `${name} created`,
            content: { 'application/json': { schema: { '$ref': `#/components/schemas/${name}` } } },
          },
          422: { '$ref': '#/components/responses/ValidationError' },
        },
      },
    }

    // GET /resources/:id (show)
    // PUT /resources/:id (update)
    // PATCH /resources/:id (patch)
    // DELETE /resources/:id (destroy)
    const idPath = `${basePath}/{id}`
    spec.paths[idPath] = {
      get: {
        tags: tag, summary: `Get a ${name} by ID`, operationId: `get${name}`,
        ...securityDef,
        parameters: [
          { name: 'id', in: 'path', required: true, schema: { type: 'string' } },
          { name: 'with', in: 'query', schema: { type: 'string' } },
        ],
        responses: {
          200: { description: `${name} found`, content: { 'application/json': { schema: { '$ref': `#/components/schemas/${name}` } } } },
          404: { '$ref': '#/components/responses/NotFound' },
        },
      },
      put: {
        tags: tag, summary: `Update a ${name}`, operationId: `update${name}`,
        ...securityDef,
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        requestBody: { required: true, content: { 'application/json': { schema: { '$ref': `#/components/schemas/Update${name}Input` } } } },
        responses: {
          200: { description: `${name} updated`, content: { 'application/json': { schema: { '$ref': `#/components/schemas/${name}` } } } },
          404: { '$ref': '#/components/responses/NotFound' },
          422: { '$ref': '#/components/responses/ValidationError' },
        },
      },
      patch: {
        tags: tag, summary: `Partially update a ${name}`, operationId: `patch${name}`,
        ...securityDef,
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        requestBody: { required: true, content: { 'application/json': { schema: { '$ref': `#/components/schemas/Update${name}Input` } } } },
        responses: {
          200: { description: `${name} updated`, content: { 'application/json': { schema: { '$ref': `#/components/schemas/${name}` } } } },
          404: { '$ref': '#/components/responses/NotFound' },
          422: { '$ref': '#/components/responses/ValidationError' },
        },
      },
      delete: {
        tags: tag, summary: `Delete a ${name}`, operationId: `delete${name}`,
        ...securityDef,
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        responses: {
          204: { description: `${name} deleted` },
          404: { '$ref': '#/components/responses/NotFound' },
        },
      },
    }

    // Soft delete routes
    if (softDeletes) {
      spec.paths[`${basePath}/trashed`] = {
        get: {
          tags: tag, summary: `List trashed ${name} records`, operationId: `listTrashed${name}`,
          ...securityDef,
          parameters: [
            { name: 'page',     in: 'query', schema: { type: 'integer' } },
            { name: 'per_page', in: 'query', schema: { type: 'integer' } },
          ],
          responses: {
            200: { description: 'Soft-deleted records', content: { 'application/json': { schema: { '$ref': `#/components/schemas/${name}Page` } } } },
          },
        },
      }
      spec.paths[`${basePath}/{id}/restore`] = {
        post: {
          tags: tag, summary: `Restore a soft-deleted ${name}`, operationId: `restore${name}`,
          ...securityDef,
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: {
            200: { description: `${name} restored`, content: { 'application/json': { schema: { '$ref': `#/components/schemas/${name}` } } } },
            404: { '$ref': '#/components/responses/NotFound' },
          },
        },
      }
    }
  }

  // ── Shared component schemas ──────────────────────────────────────────────
  spec.components.schemas['PaginationMeta'] = {
    type: 'object',
    properties: {
      total:        { type: 'integer' },
      per_page:     { type: 'integer' },
      current_page: { type: 'integer' },
      last_page:    { type: 'integer' },
      has_more:     { type: 'boolean' },
    },
  }

  spec.components.responses = {
    NotFound: {
      description: 'Resource not found',
      content: { 'application/json': { schema: { type: 'object', properties: { error: { type: 'string' } } } } },
    },
    ValidationError: {
      description: 'Validation failed',
      content: { 'application/json': { schema: {
        type: 'object',
        properties: { errors: { type: 'object', additionalProperties: { type: 'array', items: { type: 'string' } } } },
      } } },
    },
    Forbidden: {
      description: 'Access denied',
      content: { 'application/json': { schema: { type: 'object', properties: { error: { type: 'string' } } } } },
    },
  }

  return spec
}

function lcFirst(s) { return s[0].toLowerCase() + s.slice(1) }
function toKebab(s) { return s.replace(/([A-Z])/g, '-$1').toLowerCase().replace(/^-/, '') }
