/**
 * @eloquentjs/codegen — TypeScript Types Template
 *
 * Generates TypeScript interfaces and types from ModelSchemas.
 * CLI: eloquent generate:types
 */

/**
 * Generate TypeScript interface + helper types for one model.
 * @param {ModelSchema} schema
 * @param {object} opts
 * @returns {string}
 */
export function generateTypeScriptTypes(schema, opts = {}) {
  const {
    includeRelations    = true,
    includeCreateInput  = true,
    includeUpdateInput  = true,
    includeWhereInput   = false,
    strict              = true,
  } = opts

  const { name, fields, relations, softDeletes } = schema
  const q = strict ? '' : '?'   // strict: all non-null fields required; loose: everything optional

  const lines = []

  // ── Main interface ────────────────────────────────────────────────────────
  lines.push(`export interface ${name} {`)
  for (const f of fields) {
    const optional = f.nullable || f.isTimestamp || f.isSoftDelete ? '?' : ''
    const tsType   = f.isPk ? 'string' : f.tsType
    lines.push(`  ${f.name}${optional}: ${tsType}`)
  }

  if (includeRelations) {
    for (const rel of relations) {
      const relType = rel.isList ? `${rel.related}[]` : rel.related
      lines.push(`  ${rel.name}?: ${relType} | null`)
    }
  }
  lines.push('}', '')

  // ── CreateInput ───────────────────────────────────────────────────────────
  if (includeCreateInput) {
    const inputFields = fields.filter(f => !f.isPk && !f.isTimestamp && !f.isSoftDelete && !f.hidden)
    lines.push(`export interface Create${name}Input {`)
    for (const f of inputFields) {
      lines.push(`  ${f.name}?: ${f.tsType}`)
    }
    lines.push('}', '')
  }

  // ── UpdateInput ───────────────────────────────────────────────────────────
  if (includeUpdateInput) {
    const inputFields = fields.filter(f => !f.isPk && !f.isTimestamp && !f.isSoftDelete && !f.hidden)
    lines.push(`export interface Update${name}Input {`)
    for (const f of inputFields) {
      lines.push(`  ${f.name}?: ${f.tsType}`)
    }
    lines.push('}', '')
  }

  // ── WhereInput ────────────────────────────────────────────────────────────
  if (includeWhereInput) {
    lines.push(`export interface ${name}WhereInput {`)
    for (const f of fields) {
      lines.push(`  ${f.name}?: ${f.tsType} | null`)
    }
    lines.push(`  AND?: ${name}WhereInput[]`)
    lines.push(`  OR?: ${name}WhereInput[]`)
    lines.push('}', '')
  }

  return lines.join('\n')
}

/**
 * Generate a complete TypeScript declaration file for one or more models.
 * @param {ModelSchema[]} schemas
 * @param {object} opts
 * @returns {string}
 */
export function generateTypeScriptFile(schemas, opts = {}) {
  const { header = true, moduleFormat = 'esm' } = opts
  const lines = []

  if (header) {
    lines.push('// Auto-generated by @eloquentjs/codegen')
    lines.push(`// Generated: ${new Date().toISOString()}`)
    lines.push('// Do not edit manually — re-run: eloquent generate:types')
    lines.push('')
  }

  // Shared pagination types
  lines.push('export interface PaginationMeta {')
  lines.push('  total: number')
  lines.push('  per_page: number')
  lines.push('  current_page: number')
  lines.push('  last_page: number')
  lines.push('  has_more: boolean')
  lines.push('}')
  lines.push('')
  lines.push('export interface PaginatedResult<T> {')
  lines.push('  data: T[]')
  lines.push('  meta: PaginationMeta')
  lines.push('}')
  lines.push('')

  for (const schema of schemas) {
    lines.push(`// ─── ${schema.name} ${'─'.repeat(60 - schema.name.length)}`)
    lines.push(generateTypeScriptTypes(schema, opts))
  }

  return lines.join('\n')
}
