export default {
  testEnvironment: 'node',
  transform: {},
  moduleNameMapper: {
    '^@eloquentjs/core$':              '<rootDir>/packages/core/src/index.js',
    '^@eloquentjs/pgsql$':             '<rootDir>/packages/pgsql/src/index.js',
    '^@eloquentjs/sqlite$':            '<rootDir>/packages/sqlite/src/index.js',
    '^@eloquentjs/mongodb$':           '<rootDir>/packages/mongodb/src/index.js',
    '^@eloquentjs/realtime$':          '<rootDir>/packages/realtime/src/index.js',
    '^@eloquentjs/graphql$':           '<rootDir>/packages/graphql/src/index.js',
    '^@eloquentjs/api$':               '<rootDir>/packages/api/src/index.js',
    '^@eloquentjs/cli$':               '<rootDir>/packages/cli/src/index.js',
    '^@eloquentjs/validator$':         '<rootDir>/packages/validator/src/index.js',
    '^@eloquentjs/validator/schema':   '<rootDir>/packages/validator/src/Schema.js',
    '^@eloquentjs/validator/rule':     '<rootDir>/packages/validator/src/Rule.js',
    '^@eloquentjs/validator/rules':    '<rootDir>/packages/validator/src/rules/index.js',
    '^@eloquentjs/validator/adapters': '<rootDir>/packages/validator/src/adapters/index.js',
    '^@eloquentjs/codegen$':           '<rootDir>/packages/codegen/src/index.js',
    '^@eloquentjs/codegen/introspect': '<rootDir>/packages/codegen/src/introspect.js',
    '^@eloquentjs/codegen/templates':  '<rootDir>/packages/codegen/src/templates/index.js',
    '^@eloquentjs/codegen/render':     '<rootDir>/packages/codegen/src/render.js',
    '^@eloquentjs/mcp$':               '<rootDir>/packages/mcp/src/index.js',
    '^@eloquentjs/mcp/tools':          '<rootDir>/packages/mcp/src/tools/index.js',
  },
  testMatch: ['**/tests/**/*.test.js'],
  collectCoverageFrom: ['packages/*/src/**/*.js'],
}
