export default {
  testEnvironment: 'node',
  transform: {},
  moduleNameMapper: {
    '^@eloquentjs/core$':              '<rootDir>/packages/core/src/index.js',
    '^@eloquentjs/core/testing$':      '<rootDir>/packages/core/src/testing/conformance.js',
    '^@eloquentjs/pgsql$':             '<rootDir>/packages/pgsql/src/index.js',
    '^@eloquentjs/sqlite$':            '<rootDir>/packages/sqlite/src/index.js',
    '^@eloquentjs/mongodb$':           '<rootDir>/packages/mongodb/src/index.js',
    '^@eloquentjs/realtime$':          '<rootDir>/packages/realtime/src/index.js',
    '^@eloquentjs/graphql$':           '<rootDir>/packages/graphql/src/index.js',
    '^@eloquentjs/api$':               '<rootDir>/packages/api/src/index.js',
    '^@eloquentjs/cli$':               '<rootDir>/packages/cli/src/index.js',
    '^@eloquentjs/cli/utils$':         '<rootDir>/packages/cli/src/utils.js',
    '^@eloquentjs/cli/migration-runner$': '<rootDir>/packages/cli/src/commands/migration-runner.js',
    '^@eloquentjs/validator$':         '<rootDir>/packages/validator/src/index.js',
    '^@eloquentjs/validator/schema':   '<rootDir>/packages/validator/src/Schema.js',
    '^@eloquentjs/validator/rule':     '<rootDir>/packages/validator/src/Rule.js',
    '^@eloquentjs/validator/rules':    '<rootDir>/packages/validator/src/rules/index.js',
    '^@eloquentjs/validator/adapters': '<rootDir>/packages/validator/src/adapters/index.js',
    '^@eloquentjs/codegen$':           '<rootDir>/packages/codegen/src/index.js',
    '^@eloquentjs/codegen/introspect': '<rootDir>/packages/codegen/src/introspect.js',
    '^@eloquentjs/codegen/templates':  '<rootDir>/packages/codegen/src/templates/index.js',
    '^@eloquentjs/codegen/render':     '<rootDir>/packages/codegen/src/render.js',
    '^@eloquentjs/mcp$':               '<rootDir>/packages/mcp/src/index.js',
    '^@eloquentjs/mcp/tools':          '<rootDir>/packages/mcp/src/tools/index.js',
  },
  testMatch: ['**/tests/**/*.test.js'],
  collectCoverageFrom: ['packages/*/src/**/*.js'],
  // A floor just under the current numbers, so coverage can only go up. Raise
  // these as suites are added; do not lower them to make a build pass.
  coverageThreshold: {
    global: {
      statements: 54,
      branches: 47,
      functions: 52,
      lines: 57,
    },
  },
}
